name: Full Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java_version: [17, 18]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: mvn clean install -DskipTests -q
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
      - name: Build
        run: mvn clean package
        env:
          BUILD_PORT: 0
          BUILD_SECURE_PORT: 0
      - name: Test Result
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: JUnit ${{ matrix.kind }} ${{ matrix.java_version }} ${{ matrix.os }}
          report_paths: '*/target/*/TEST-*.xml'
